### ISSUE TITLE
[/usr/lib/x86_64-linux-gnu/libc.a: no space left on device] space issue on Mac OS.

### ISSUE THREAD

**Issue by MVSTeja06** [ODU-CGA-CubeSat/kasm-sealion-workspace#1]
Happens when we run :- **docker-compose pull**

**NOTE** :- Happens on docker desktop, MacOS Monterrey.

**Comment by MVSTeja06** [comment]
Bumping the docker image size to 16 gigs resolved the issue.

**Comment by capsulecorplab** [comment]
closing, as README includes updated docker desktop notes as per https://github.com/ODU-CGA-CubeSat/kasm-sealion-workspace/commit/c8404c8bf3b029182f6a3e3587203c517cd6ddfe
